// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Z0kT3cULXjsdyyqubNazPSn78lMV7-U',
    appId: '1:413955757345:web:f7239c4ba2d8f678cc9a60',
    messagingSenderId: '413955757345',
    projectId: 'instagram-ce0b8',
    authDomain: 'instagram-ce0b8.firebaseapp.com',
    storageBucket: 'instagram-ce0b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvki92mafpWpHRUZanLSgUUQ4hm5_Tf5c',
    appId: '1:413955757345:android:37007ffcf95daa49cc9a60',
    messagingSenderId: '413955757345',
    projectId: 'instagram-ce0b8',
    storageBucket: 'instagram-ce0b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_PvkHjoTFcfGTG2CLv2Vt40mQaPkHlNM',
    appId: '1:413955757345:ios:02b631cab94a4d19cc9a60',
    messagingSenderId: '413955757345',
    projectId: 'instagram-ce0b8',
    storageBucket: 'instagram-ce0b8.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_PvkHjoTFcfGTG2CLv2Vt40mQaPkHlNM',
    appId: '1:413955757345:ios:02b631cab94a4d19cc9a60',
    messagingSenderId: '413955757345',
    projectId: 'instagram-ce0b8',
    storageBucket: 'instagram-ce0b8.appspot.com',
    iosBundleId: 'com.example.instagram',
  );
}
